export const SliderData = [
  {
    id: 0,
    image: "./photos/Charlie.jpg",
    name: "Charlie Lowe",
    bio: "",
    role: "Snare Tech",
  },
  {
    id: 1,
    image: "./photos/Nick.jpg",
    name: "Nick McConnaughey",
    bio: "",
    role: "Front Ensemble Coordinator",
  },
  {
    id: 2,
    image: "./photos/Sami.jpg",
    name: "Sami Maddox",
    bio: "",
    role: "Visual Tech",
  },
  {
    id: 3,
    image: "./photos/Rob.jpg",
    name: "Rob Law",
    bio: "",
    role: "Battery Coordinator",
  },
  {
    id: 4,
    image: "./photos/Carlos.jpg",
    name: "Carlos Martinez",
    bio: "",
    role: "Cymbal Tech",
  },
  {
    id: 5,
    image: "./photos/Elly.jpg",
    name: "Elly Hutson",
    bio: "",
    role: "Visual Tech",
  },
  {
    id: 6,
    image: "./photos/Spencer.jpg",
    name: "Spencer Nielson",
    bio: "",
    role: "Bass Drum Tech",
  },
  {
    id: 7,
    image: "./photos/Kross.jpg",
    name: "Kross Torregrossa",
    bio: "",
    role: "Quad Tech",
  },
];
