export const SliderData = [
  {
    id: 0,
    image: "./photos/Charlie.jpg",
    name: "Charlie Lowe",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non tristique elit, sit amet hendrerit quam. Sed malesuada arcu ut orci dictum aliquam. Aliquam erat volutpat. Suspendisse lorem libero, consectetur id pharetra vitae, pellentesque porta velit. Vestibulum nec sapien non sapien consequat sollicitudin consectetur id est. Quisque mattis ut neque commodo feugiat. Cras in metus ex. Nulla non gravida enim, eu rutrum nisl. Duis erat justo, viverra in nibh vitae, vehicula sodales mauris. Nam accumsan mauris eget mi egestas, id luctus tortor volutpat.",
    role: "Snare Tech",
  },
  {
    id: 1,
    image: "./photos/Nick.jpg",
    name: "Nick McConnaughey",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non tristique elit, sit amet hendrerit quam. Sed malesuada arcu ut orci dictum aliquam. Aliquam erat volutpat. Suspendisse lorem libero, consectetur id pharetra vitae, pellentesque porta velit. Vestibulum nec sapien non sapien consequat sollicitudin consectetur id est. Quisque mattis ut neque commodo feugiat. Cras in metus ex. Nulla non gravida enim, eu rutrum nisl. Duis erat justo, viverra in nibh vitae, vehicula sodales mauris. Nam accumsan mauris eget mi egestas, id luctus tortor volutpat. Quisque suscipit, ipsum sit amet vestibulum ornare, ligula lacus porta lectus, pretium iaculis dolor sem non lectus. Quisque ut maximus quam, at mollis nisi.Phasellus mollis felis at augue fermentum consequat. Donec id imperdiet massa. Vivamus urna tellus, sodales ac pellentesque a, accumsan eu felis. Nam nec nunc nec tellus imperdiet varius. Etiam quis viverra massa. Donec vitae urna nibh. Vivamus eget orci condimentum lorem ornare pretium. Praesent sed leo nec urna molestie lacinia. Fusce risus erat, tempus eu dignissim a, posuere id purus. Etiam id elit euismod, volutpat ligula nec, tristique mauris. Aliquam malesuada commodo hendrerit. Nullam in viverra nibh, finibus fermentum elit. Morbi vel venenatis odio, a sodales lectus. Curabitur velit ligula, viverra et tincidunt quis, egestas id ante.",
    role: "Front Ensemble Coordinator",
  },
  {
    id: 2,
    image: "./photos/Sami.jpg",
    name: "Sami Maddox",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non tristique elit, sit amet hendrerit quam. Sed malesuada arcu ut orci dictum aliquam. Aliquam erat volutpat. Suspendisse lorem libero, consectetur id pharetra vitae, pellentesque porta velit. Vestibulum nec sapien non sapien consequat sollicitudin consectetur id est. Quisque mattis ut neque commodo feugiat. Cras in metus ex. Nulla non gravida enim, eu rutrum nisl. Duis erat justo, viverra in nibh vitae, vehicula sodales mauris. Nam accumsan mauris eget mi egestas, id luctus tortor volutpat.",
    role: "Visual Tech",
  },
  {
    id: 3,
    image: "./photos/Rob.jpg",
    name: "Rob Law",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non tristique elit, sit amet hendrerit quam. Sed malesuada arcu ut orci dictum aliquam. Aliquam erat volutpat. Suspendisse lorem libero, consectetur id pharetra vitae, pellentesque porta velit. Vestibulum nec sapien non sapien consequat sollicitudin consectetur id est.",
    role: "Battery Coordinator",
  },
  {
    id: 4,
    image: "./photos/Carlos.jpg",
    name: "Carlos Martinez",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non tristique elit, sit amet hendrerit quam. Sed malesuada arcu ut orci dictum aliquam. Aliquam erat volutpat. Suspendisse lorem libero, consectetur id pharetra vitae, pellentesque porta velit. Vestibulum nec sapien non sapien consequat sollicitudin consectetur id est. Quisque mattis ut neque commodo feugiat. Cras in metus ex. Nulla non gravida enim, eu rutrum nisl. Duis erat justo, viverra in nibh vitae, vehicula sodales mauris. Nam accumsan mauris eget mi egestas, id luctus tortor volutpat.",
    role: "Cymbal Tech",
  },
  {
    id: 5,
    image: "./photos/Elly.jpg",
    name: "Elly Hutson",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non tristique elit, sit amet hendrerit quam. Sed malesuada arcu ut orci dictum aliquam. Aliquam erat volutpat. Suspendisse lorem libero, consectetur id pharetra vitae, pellentesque porta velit. Vestibulum nec sapien non sapien consequat sollicitudin consectetur id est. Quisque mattis ut neque commodo feugiat. Cras in metus ex. Nulla non gravida enim, eu rutrum nisl. Duis erat justo, viverra in nibh vitae, vehicula sodales mauris. Nam accumsan mauris eget mi egestas, id luctus tortor volutpat.",
    role: "Visual Tech",
  },
  {
    id: 6,
    image: "./photos/Spencer.jpg",
    name: "Spencer Nielson",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non tristique elit, sit amet hendrerit quam. Sed malesuada arcu ut orci dictum aliquam. Aliquam erat volutpat. Suspendisse lorem libero, consectetur id pharetra vitae, pellentesque porta velit. Vestibulum nec sapien non sapien consequat sollicitudin consectetur id est. Quisque mattis ut neque commodo feugiat. Cras in metus ex. Nulla non gravida enim, eu rutrum nisl. Duis erat justo, viverra in nibh vitae, vehicula sodales mauris. Nam accumsan mauris eget mi egestas, id luctus tortor volutpat.",
    role: "Bass Drum Tech",
  },
  {
    id: 7,
    image: "./photos/Kross.jpg",
    name: "Kross Torregrossa",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non tristique elit, sit amet hendrerit quam. Sed malesuada arcu ut orci dictum aliquam. Aliquam erat volutpat. Suspendisse lorem libero, consectetur id pharetra vitae, pellentesque porta velit. Vestibulum nec sapien non sapien consequat sollicitudin consectetur id est. Quisque mattis ut neque commodo feugiat. Cras in metus ex. Nulla non gravida enim, eu rutrum nisl. Duis erat justo, viverra in nibh vitae, vehicula sodales mauris. Nam accumsan mauris eget mi egestas, id luctus tortor volutpat.",
    role: "Quad Tech",
  },
  {
    id: 8,
    image: "./photos/Kristen.jpg",
    name: "Kristen Doohan",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non tristique elit, sit amet hendrerit quam. Sed malesuada arcu ut orci dictum aliquam. Aliquam erat volutpat. Suspendisse lorem libero, consectetur id pharetra vitae, pellentesque porta velit. Vestibulum nec sapien non sapien consequat sollicitudin consectetur id est. Quisque mattis ut neque commodo feugiat. Cras in metus ex. Nulla non gravida enim, eu rutrum nisl. Duis erat justo, viverra in nibh vitae, vehicula sodales mauris. Nam accumsan mauris eget mi egestas, id luctus tortor volutpat.",
    role: "Visual Tech",
  },
];
